version: '3.1'
services:
    php:
      build: .
      volumes:
        - ./html:/var/www/html
      ports:
        - '8080:80'
      links:
        - mongo-server
  #mongo
    mongo-server:
      image: mongo:4.2.0
      restart: always
      ports:
        - '27017:27017'